name: Run Space Weather Alert

on:
  schedule:
    - cron: '*/30 13-20 * * *'
  workflow_dispatch:

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    env:
      TZ: Europe/Moscow
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4

      - name: Установка R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'
          use-public-rspm: true

      - name: Установка системных библиотек
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            pkg-config \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libudunits2-dev \
            libgdal-dev \
            libgeos-dev \
            libproj-dev \
            libfontconfig1-dev \
            libfreetype6-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libpng-dev

      - name: Очистка возможного битого кэша
        run: |
          rm -rf ~/R/x86_64-pc-linux-gnu-library
          rm -rf /home/runner/R/Library

      - name: Установка пакетов R
        run: |
          Rscript -e 'options(repos = c(CRAN = "https://cloud.r-project.org"))'
          Rscript -e 'install.packages(c("rlang","ggplot2","dplyr","readr","httr","jsonlite"))'

      - name: Проверка пакетов
        run: |
          Rscript -e 'library(httr)'
          Rscript -e 'library(jsonlite)'
          Rscript -e 'library(ggplot2)'
          Rscript -e 'library(dplyr)'
          Rscript -e 'print("Все пакеты успешно загружены!")'

      - name: Запуск главного скрипта
        run: |
          Rscript scripts/main.R
